# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: glangloi <glangloi@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/10/31 23:27:27 by glangloi          #+#    #+#              #
#    Updated: 2015/10/31 23:27:32 by glangloi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRC = ./ft_display_file.c

FLAG = -Wall -Werror -Wextra

all: $(NAME)

$(NAME):
		gcc $(FLAG) $(SRC) -o $(NAME)

clean:
		/bin/rm -rf

fclean: clean
		/bin/rm -rf $(NAME)
