# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: glangloi <glangloi@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/10/31 23:41:04 by glangloi          #+#    #+#              #
#    Updated: 2015/12/10 04:17:01 by glangloi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_cat

SRC = ft_cat.c

all:
		gcc -c -Wall -Wextra -Werror $(SRC)
			gcc -o $(NAME) ft_cat.o

clean:
		rm -f ft_cat.o

fclean: clean
		rm -f $(NAME)
